# Generated by Django 2.2.12 on 2020-06-10 23:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 23, 19, 35, 336755, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
